# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release tagged build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout mod repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Set release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up JDK 8
        run: sudo apt-get update && sudo apt-get install openjdk-8-jdk-headless && sudo update-java-alternatives -s java-1.8.0-openjdk-amd64

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build thermos
        run: JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 ./gradlew setupCauldron jar packageBundle --info

      - name: Release under current tag
        run: gh release create "${RELEASE_VERSION}" --generate-notes ./build/distributions/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Maven not configured in gradle yet
      # - name: Publish to Maven
      #   run: ./gradlew publish
      #   env:
      #     MAVEN_USER: ${{ secrets.MAVEN_USER }}
      #     MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      #   if: ${{ env.MAVEN_USER != '' }}
